# Generated by Django 5.1.4 on 2025-01-14 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='content',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='position',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='type',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='slide',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='slide',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/backgrounds/'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='SlideElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('shape', 'Shape')], max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('font_size', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='presentations.slide')),
            ],
        ),
    ]
