# Generated by Django 5.1.4 on 2025-01-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_remove_presentation_user_remove_slide_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
