# Generated by Django 5.1.4 on 2025-01-27 12:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_presentation_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='title',
        ),
        migrations.AddField(
            model_name='presentation',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentation',
            name='subject',
            field=models.CharField(choices=[('Calculus', 'Математический анализ'), ('Algebra', 'Алгебра'), ('Discrete', 'Дискретная математика')], default='Calculus', max_length=50),
        ),
        migrations.AddField(
            model_name='slide',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='slide',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='slide',
            name='position',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='slide',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('graph', 'Graph')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='slide',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SlideElement',
        ),
    ]
