# Generated by Django 5.1.4 on 2025-02-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0005_alter_presentation_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='order',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='position',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='type',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(choices=[('text', 'Текстовый'), ('test', 'Проверочный'), ('questionnaire', 'Вопросник')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
