# Generated by Django 5.1.4 on 2025-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0007_slide_slide_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='slide',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
