# Generated by Django 5.1.4 on 2025-02-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0008_slide_answers_slide_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='answers',
        ),
    ]
