# Generated by Django 5.1.4 on 2025-03-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0009_remove_slide_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
